### ISSUE TITLE
Re-think the title

### ISSUE THREAD

**Issue by JJ** [raiben/tropes_open_data#2]
Basically, you're publishing a report on a new dataset. That's what the title must be about: "here's this dataset, here's what you can use it for". For instance

"PicTropes: a film trope dataset"

Maybe add "for machine learning and content generation", but that's implicit

"Overview of PicTropes, a film trope dataset"

"I've seen that one: analyzing film tropes using the PicTropes dataset"

**Comment by rhgarcia** [comment]
Hi, 
I changed the title following your suggestions. I chose "Overview of PicTropes, a film trope dataset. Preliminary technical report". The second part was added just because I left some open questions and ways to improve the dataset, so the report could also be improved... Do you agree?

**Comment by JJ** [comment]
Preliminary technical report is not needed.
