### ISSUE TITLE
Explain the reason the movies with more tropes are the contemporary ones

### ISSUE THREAD

**Issue by fergunet** [raiben/tropes_open_data#4]
It seems that the movies with the most tropes are the most popular these days. Should we mention that? (maybe it is also interesting perform a study on time of the contributions of the site, or maybe grouping by decade or something like that)

**Comment by rhgarcia** [comment]
Hi,
This is explained (as far as I could) in the Discussion. Could you please take a look and tell me if it makes sense and if there's something to change? Could you tell me if this is interesting for the conclusions?
Thank you!
