### ISSUE TITLE
Add a paragraph explaining why this study is interesting for your thesis

### ISSUE THREAD

**Issue by fergunet** [raiben/tropes_open_data#5]
This study is necessary in the context of massive... because it will help/facilitate/whatever...

**Comment by rhgarcia** [comment]
Hi,
This is in WIP: 
Although I haven't written the conclusions, I tried to explain this issue in the third paragraph of the Introduction. Could you please take a look? Could you give me hint's about how to include it in the conclusions?
Thank you!
